export const languages = {
  en: "English",
  ta: "தமிழ்",
  ml: "മലയാളം",
  hi: "हिंदी",
} as const;

export type Language = keyof typeof languages;
export type TranslationKey = keyof typeof translations.en;

export const translations = {
  en: {
    home: "Home", about: "About Us", openings: "Current Openings", process: "How We Work", safety: "Safety & Anti-Scam", testimonials: "Testimonials", contact: "Contact",
    whatsapp: "WhatsApp us", heroEyebrow: "Ethical recruitment since 2012", heroTitle: "Your Journey from Home to a Career in the Gulf, Made Simple and Safe.", heroBody: "Finding work abroad is a big decision. We connect you with verified, tax-free career opportunities across Saudi Arabia, the UAE, Qatar and Oman, and stay beside you from your first question to your first day at work.", viewVacancies: "View open vacancies", enroll: "Enroll for next batch", promise: "Our promise", promiseTitle: "A clear path. A fair contract. A real future.", promiseOne: "Direct employer interviews", promiseTwo: "Government-approved paperwork", promiseThree: "Pre-departure orientation", safetyPromise: "See our safety promise", standard: "The RAK standard", standardTitle: "No guesswork. Just the next right step.", standardBody: "Moving abroad is a big decision. We know there may be worry and questions. We are here to make every document, conversation and commitment understandable.", exploreProcess: "Explore how we work", openRoles: "Open roles", nextRole: "Your next role could be here.", seeVacancies: "See all vacancies", nextBatch: "Next batch enrollment", nextBatchTitle: "The right opening may not be listed yet.", nextBatchBody: "Share your experience with us and let our placement desk come to you.", statsExperience: "Years of industry experience", statsPlacements: "Successful job placements", statsLegal: "Legal documentation", statsEmployers: "Verified GCC employers",
  },
  ta: {
    home: "முகப்பு", about: "எங்களைப் பற்றி", openings: "தற்போதைய வேலைவாய்ப்புகள்", process: "நாங்கள் எப்படி உதவுகிறோம்", safety: "பாதுகாப்பு மற்றும் மோசடி தடுப்பு", testimonials: "வெற்றிக் கதைகள்", contact: "தொடர்பு கொள்ளுங்கள்",
    whatsapp: "WhatsApp மூலம் பேசுங்கள்", heroEyebrow: "2012 முதல் வளைகுடா வேலைவாய்ப்பில் நம்பகமான வழிகாட்டுதல்", heroTitle: "உங்கள் ஊரிலிருந்து வளைகுடாவில் நம்பகமான வேலை வரை — ஒவ்வொரு அடியிலும் RAK உங்களுடன்.", heroBody: "வெளிநாட்டில் வேலை தேடும்போது சரியான தகவலும் நம்பகமான வழிகாட்டுதலும் அவசியம். சவுதி அரேபியா, ஐக்கிய அரபு அமீரகம், கத்தார், ஓமன் ஆகிய நாடுகளில் சரிபார்க்கப்பட்ட நிறுவனங்களின் சட்டபூர்வ வேலைவாய்ப்புகளைத் தேர்ந்தெடுக்கவும், ஆவணங்கள் முதல் பயணம் வரை அடுத்த படி என்ன என்பதைத் தெளிவாகப் புரிந்துகொள்ளவும் நாங்கள் உங்களுக்கு உதவுகிறோம்.", viewVacancies: "சரிபார்க்கப்பட்ட வேலைவாய்ப்புகளைப் பார்க்க", enroll: "அடுத்த வாய்ப்புக்குப் பதிவு செய்யுங்கள்", promise: "எங்கள் அணுகுமுறை", promiseTitle: "வேலை கிடைப்பது மட்டும் இலக்கு அல்ல; பாதுகாப்பாகச் சென்று நிம்மதியாகத் தொடங்க வேண்டும்.", promiseOne: "நிறுவனத்துடன் நேரடி நேர்காணல்", promiseTwo: "ஆவணங்களை முறையாகச் சரிபார்த்தல்", promiseThree: "புறப்படும் முன் தெளிவான வழிகாட்டுதல்", safetyPromise: "எங்கள் பாதுகாப்பு நடைமுறையைப் பாருங்கள்", standard: "உங்கள் பயணத்தில் RAK துணை", standardTitle: "செலவுகள், ஆவணங்கள், அடுத்த படி — அனைத்தும் முன்கூட்டியே தெளிவாக.", standardBody: "வெளிநாட்டில் வேலைக்குச் செல்வது குடும்பத்துடன் ஆலோசித்து எடுக்க வேண்டிய முடிவு. வேலை, சம்பளம், ஒப்பந்தம், விசா, மருத்துவப் பரிசோதனை என ஒவ்வொரு கட்டத்தையும் எளிய மொழியில் விளக்குகிறோம்; உங்களுக்கு நம்பிக்கை வந்த பிறகே அடுத்த படிக்குச் செல்ல உதவுகிறோம்.", exploreProcess: "எங்கள் செயல்முறையை அறியுங்கள்", openRoles: "சரிபார்க்கப்பட்ட வேலைவாய்ப்புகள்", nextRole: "உங்களுக்கு ஏற்ற அடுத்த வாய்ப்பு இங்கே இருக்கலாம்.", seeVacancies: "அனைத்து வேலைவாய்ப்புகளையும் பார்க்க", nextBatch: "அடுத்த வேலைவாய்ப்பு குழு", nextBatchTitle: "உங்களுக்கு ஏற்ற வாய்ப்பு இன்னும் பட்டியலில் இல்லாமலும் இருக்கலாம்.", nextBatchBody: "உங்கள் அனுபவம் மற்றும் விருப்பத்தை எங்களிடம் பகிருங்கள். பொருத்தமான வேலை கிடைத்தவுடன் எங்கள் குழு உங்களைத் தொடர்புகொண்டு அடுத்த படிகளைத் தெளிவாகச் சொல்லும்.", statsExperience: "ஆண்டுகளின் தொழில் அனுபவம்", statsPlacements: "வெற்றிகரமாக பணியில் சேர்ந்தவர்கள்", statsLegal: "சரிபார்க்கப்பட்ட சட்டபூர்வ ஆவணங்கள்", statsEmployers: "சரிபார்க்கப்பட்ட GCC நிறுவனங்கள்",
  },
  ml: {
    home: "ഹോം", about: "ഞങ്ങളെക്കുറിച്ച്", openings: "നിലവിലെ ജോലികൾ", process: "ഞങ്ങൾ എങ്ങനെ പ്രവർത്തിക്കുന്നു", safety: "സുരക്ഷ", testimonials: "വിജയകഥകൾ", contact: "ബന്ധപ്പെടുക", whatsapp: "WhatsApp ബന്ധപ്പെടുക", heroEyebrow: "2012 മുതൽ സത്യസന്ധമായ റിക്രൂട്ട്മെന്റ്", heroTitle: "വീട്ടിൽ നിന്ന് ഗൾഫിലെ ജോലിയിലേക്കുള്ള നിങ്ങളുടെ യാത്ര ലളിതവും സുരക്ഷിതവുമാക്കാം.", heroBody: "സൗദി അറേബ്യ, UAE, ഖത്തർ, ഒമാൻ എന്നിവിടങ്ങളിലെ വിശ്വസനീയമായ നികുതിയില്ലാത്ത അവസരങ്ങളുമായി നിങ്ങളെ ബന്ധിപ്പിക്കുന്നു.", viewVacancies: "ജോലികൾ കാണുക", enroll: "അടുത്ത ബാച്ചിൽ രജിസ്റ്റർ ചെയ്യുക", promise: "ഞങ്ങളുടെ വാഗ്ദാനം", promiseTitle: "വ്യക്തമായ വഴി. ന്യായമായ കരാർ. യഥാർത്ഥ ഭാവി.", promiseOne: "നേരിട്ടുള്ള തൊഴിലുടമ അഭിമുഖങ്ങൾ", promiseTwo: "സർക്കാർ അംഗീകരിച്ച രേഖകൾ", promiseThree: "യാത്രയ്ക്ക് മുമ്പുള്ള മാർഗനിർദേശം", safetyPromise: "ഞങ്ങളുടെ സുരക്ഷാ വാഗ്ദാനം", standard: "RAK നിലവാരം", standardTitle: "ഊഹമില്ല. അടുത്ത ശരിയായ ചുവട് മാത്രം.", standardBody: "വിദേശത്തേക്ക് പോകുന്നത് വലിയ തീരുമാനമാണ്. ഓരോ രേഖയും വ്യക്തമായി മനസ്സിലാക്കാൻ ഞങ്ങൾ നിങ്ങളോടൊപ്പമുണ്ട്.", exploreProcess: "ഞങ്ങളുടെ രീതി കാണുക", openRoles: "തുറന്ന ജോലികൾ", nextRole: "നിങ്ങളുടെ അടുത്ത ജോലി ഇവിടെ ആയിരിക്കാം.", seeVacancies: "എല്ലാ ജോലികളും കാണുക", nextBatch: "അടുത്ത ബാച്ച് രജിസ്ട്രേഷൻ", nextBatchTitle: "ശരിയായ അവസരം ഇതുവരെ പട്ടികപ്പെടുത്തിയിട്ടില്ലായിരിക്കാം.", nextBatchBody: "നിങ്ങളുടെ പരിചയം ഞങ്ങളുമായി പങ്കിടൂ.", statsExperience: "വ്യവസായ പരിചയ വർഷങ്ങൾ", statsPlacements: "വിജയകരമായ നിയമനങ്ങൾ", statsLegal: "നിയമപരമായ രേഖകൾ", statsEmployers: "പരിശോധിച്ച GCC തൊഴിലുടമകൾ",
  },
  hi: {
    home: "होम", about: "हमारे बारे में", openings: "वर्तमान नौकरियां", process: "हम कैसे काम करते हैं", safety: "सुरक्षा", testimonials: "सफलता की कहानियां", contact: "संपर्क", whatsapp: "WhatsApp संपर्क", heroEyebrow: "2012 से ईमानदार भर्ती", heroTitle: "घर से खाड़ी में करियर तक का आपका सफर सरल और सुरक्षित बनाया गया है।", heroBody: "सऊदी अरब, UAE, कतर और ओमान में भरोसेमंद टैक्स-फ्री अवसरों से आपको जोड़ना हमारा काम है। हर कदम पर हमारी टीम आपके साथ है।", viewVacancies: "नौकरियां देखें", enroll: "अगले बैच में पंजीकरण", promise: "हमारा वादा", promiseTitle: "स्पष्ट रास्ता। उचित अनुबंध। बेहतर भविष्य।", promiseOne: "सीधे नियोक्ता के इंटरव्यू", promiseTwo: "सरकार द्वारा स्वीकृत दस्तावेज़", promiseThree: "यात्रा से पहले मार्गदर्शन", safetyPromise: "हमारी सुरक्षा प्रतिबद्धता", standard: "RAK मानक", standardTitle: "अनुमान नहीं। बस अगला सही कदम।", standardBody: "विदेश जाना बड़ा फैसला है। हर दस्तावेज़ और बातचीत को समझने योग्य बनाने के लिए हम आपके साथ हैं।", exploreProcess: "हमारी प्रक्रिया देखें", openRoles: "उपलब्ध नौकरियां", nextRole: "आपकी अगली नौकरी यहां हो सकती है।", seeVacancies: "सभी नौकरियां देखें", nextBatch: "अगला बैच पंजीकरण", nextBatchTitle: "सही अवसर अभी सूची में नहीं भी हो सकता है।", nextBatchBody: "अपना अनुभव हमारे साथ साझा करें।", statsExperience: "वर्षों का उद्योग अनुभव", statsPlacements: "सफल नौकरी प्लेसमेंट", statsLegal: "कानूनी दस्तावेज़", statsEmployers: "सत्यापित GCC नियोक्ता",
  },
} satisfies Record<Language, Record<string, string>>;